/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unicamp.ic.mc322.view.admin;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import unicamp.ic.mc322.main.Main;
import unicamp.ic.mc322.model.Empresa;
import unicamp.ic.mc322.model.Filial;
import unicamp.ic.mc322.model.Funcionario;
import unicamp.ic.mc322.model.Gerente;
import unicamp.ic.mc322.view.FrmLogin;
import unicamp.ic.mc322.view.FrmMenu;

/**
 *
 * @author ludiv
 */
public class FrmListaEmpresas extends javax.swing.JFrame {

        private Funcionario admOuDono;

        private Empresa empresaSelecionada;

        public Funcionario getAdm() {
                return admOuDono;
        }

        public void setAdm(Funcionario admOuDono) {
                this.admOuDono = admOuDono;
        }

        private void atualizarTabelaFilial() {
                DefaultTableModel model = (DefaultTableModel) tblFiliais.getModel();
                model.setRowCount(0);
                if (empresaSelecionada != null)
                        for (Filial f : empresaSelecionada.getListaFiliais()) {
                                Object[] novaLinha = { f.getId(), f.getNome(), f.getEndereco() }; // Substitua
                                // pelos
                                // dados
                                // que deseja adicionar
                                model.addRow(novaLinha);
                        }
        }

        private void atualizarTabelaEmpresa() {
                DefaultTableModel model = (DefaultTableModel) tblEmpresas.getModel();
                model.setRowCount(0);
                if (Main.listaEmpresas != null)
                        for (Empresa e : Main.listaEmpresas) {
                                Object[] novaLinha = { e.getCnpj(), e.getNome(), e.getDono().getCpf(),
                                                e.getDono().getSenha() }; // Substitua
                                // pelos
                                // dados
                                // que deseja adicionar
                                model.addRow(novaLinha);
                        }
        }

        /**
         * Creates new form FrmListaEmpresas
         */
        public FrmListaEmpresas(Funcionario admOuDono) {
                initComponents();

                this.admOuDono = admOuDono;
                if (admOuDono.getCargo().equals("Dono")) {

                        for (Empresa e : Main.listaEmpresas) {
                                if (e.getDono().getCpf().equals(admOuDono.getCpf())) {
                                        empresaSelecionada = e;
                                        atualizarTabelaFilial();
                                }
                        }

                        this.btnSalvar.setVisible(false);
                        this.btnExcluir.setVisible(false);
                        lblOu.setVisible(false);
                        lblLinkAuth.setVisible(false);

                        txtCNPJ.setText(empresaSelecionada.getCnpj());
                        txtNome.setText(empresaSelecionada.getNome());
                        txtCPF.setText(empresaSelecionada.getDono().getCpf());
                        txtNomeDono.setText(empresaSelecionada.getDono().getNome());
                        txtTelefone.setText(empresaSelecionada.getDono().getTelefone());
                        txtSenha.setText(empresaSelecionada.getDono().getSenha());

                        txtCNPJ.setEditable(false);
                        txtNome.setEditable(false);
                        txtCPF.setEditable(false);
                        txtNomeDono.setEditable(false);
                        txtTelefone.setEditable(false);
                        txtSenha.setEditable(false);
                } else {
                        atualizarTabelaEmpresa();
                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel5 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                lblLinkAuth = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                lblSair = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jPanel7 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblEmpresas = new javax.swing.JTable();
                jScrollPane2 = new javax.swing.JScrollPane();
                tblFiliais = new javax.swing.JTable();
                jLabel3 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                txtNome = new javax.swing.JTextField();
                txtCNPJ = new javax.swing.JFormattedTextField();
                jLabel13 = new javax.swing.JLabel();
                btnSalvar = new javax.swing.JButton();
                lblOu = new javax.swing.JLabel();
                btnNovaFilial = new javax.swing.JButton();
                jLabel15 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                txtNomeDono = new javax.swing.JTextField();
                txtCPF = new javax.swing.JFormattedTextField();
                txtTelefone = new javax.swing.JFormattedTextField();
                txtSenha = new javax.swing.JTextField();
                jLabel17 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                btnExcluir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowActivated(java.awt.event.WindowEvent evt) {
                                formWindowActivated(evt);
                        }
                });

                jPanel5.setBackground(new java.awt.Color(217, 217, 217));

                jLabel10.setText("Empresa>lista");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(56, 56, 56)
                                                                .addComponent(jLabel10)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel10,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                25, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jPanel6.setBackground(new java.awt.Color(208, 207, 207));

                jLabel1.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/unicamp/ic/mc322/imagens/Logo.png"))); // NOI18N

                lblLinkAuth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblLinkAuth.setText("Auth");
                lblLinkAuth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lblLinkAuth.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblLinkAuthMouseClicked(evt);
                        }
                });

                jLabel7.setBackground(new java.awt.Color(138, 138, 138));
                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 0, 0));
                jLabel7.setText("Empresas");
                jLabel7.setToolTipText("");
                jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

                lblSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblSair.setText("Logout");
                lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblSairMouseClicked(evt);
                        }
                });

                jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel11.setText("Seja Bem-vindo");

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addGap(328, 328, 328)
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblLinkAuth)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblSair)
                                                                .addGap(43, 43, 43)));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1)
                                                                .addGap(40, 40, 40))
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblLinkAuth)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(lblSair)
                                                                                .addComponent(jLabel11))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel7.setBackground(new java.awt.Color(255, 255, 255));

                tblEmpresas.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "CNPJ", "Nome", "cpf dono", "senha dono"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                tblEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblEmpresasMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblEmpresas);

                tblFiliais.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "ID", "Nome", "Endereço"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                tblFiliais.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblFiliaisMouseClicked(evt);
                        }
                });
                jScrollPane2.setViewportView(tblFiliais);

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel3.setText("Empresas");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel12.setText("Cnpj:");

                txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                try {
                        txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                                        new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel13.setText("Nome:");

                btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                btnSalvar.setText("Cadastrar/Salvar");
                btnSalvar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSalvarActionPerformed(evt);
                        }
                });

                lblOu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                lblOu.setText("OU");

                btnNovaFilial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                btnNovaFilial.setText("Nova Filial");
                btnNovaFilial.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNovaFilialActionPerformed(evt);
                        }
                });

                jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel15.setText("Nome do dono:");

                jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel16.setText("Cpf do dono:");

                txtNomeDono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                try {
                        txtCPF.setFormatterFactory(
                                        new javax.swing.text.DefaultFormatterFactory(
                                                        new javax.swing.text.MaskFormatter("###.###.###-##")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                try {
                        txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                                        new javax.swing.text.MaskFormatter("(##) # ####-####")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel17.setText("Senha do dono");

                jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel18.setText("Telefone do dono");

                btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                btnExcluir.setText("Excluir");
                btnExcluir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExcluirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(218, 218,
                                                                                                                                                218)
                                                                                                                                .addComponent(jLabel3))
                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(231, 231,
                                                                                                                                                231)
                                                                                                                                .addComponent(btnNovaFilial))
                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(293, 293,
                                                                                                                                                293)
                                                                                                                                .addComponent(lblOu))
                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(72, 72, 72)
                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(btnSalvar)
                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel16)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                                .addComponent(txtCPF,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                275,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel15)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(txtNomeDono,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                277,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                .addComponent(jLabel13)
                                                                                                                                                                                                .addComponent(jLabel12))
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                .addComponent(txtCNPJ,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                271,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                .addComponent(txtNome,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                277,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel17)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(txtSenha,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                277,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel18)
                                                                                                                                                                                .addGap(283, 283,
                                                                                                                                                                                                283))
                                                                                                                                                                .addComponent(txtTelefone,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                277,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                113,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnExcluir)
                                                                                                .addGap(105, 105, 105)))
                                                                .addGroup(jPanel7Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                705,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jScrollPane2))
                                                                .addGap(57, 57, 57)));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                302,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                25,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(47, 47, 47)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel12)
                                                                                                                .addComponent(txtCNPJ,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(39, 39, 39)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel13)
                                                                                                                .addComponent(txtNome,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(30, 30, 30)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel16)
                                                                                                                .addComponent(txtCPF,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(39, 39, 39)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel15)
                                                                                                                .addComponent(txtNomeDono,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(30, 30, 30)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(txtTelefone,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel18))
                                                                                                .addGap(39, 39, 39)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel17)
                                                                                                                .addComponent(txtSenha,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(jPanel7Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                false)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                373,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(26, 26, 26))
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(88, 88, 88)
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnSalvar)
                                                                                                                .addComponent(btnExcluir))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(lblOu)
                                                                                                .addGap(50, 50, 50)
                                                                                                .addComponent(btnNovaFilial)
                                                                                                .addGap(89, 89, 89)))));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel6,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel7,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jPanel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                77,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tblEmpresasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblEmpresasMouseClicked
                int linhaSelecionada = tblEmpresas.getSelectedRow();

                // Aqui você pode realizar as ações desejadas com a linha selecionada
                // Por exemplo, exibir os valores das células selecionadas
                Object valorCelula1 = tblEmpresas.getValueAt(linhaSelecionada, 0);
                Object valorCelula2 = tblEmpresas.getValueAt(linhaSelecionada, 1);

                txtCNPJ.setText(valorCelula1.toString());
                txtNome.setText(valorCelula2.toString());

                for (Empresa e : Main.listaEmpresas) {
                        if (e.getCnpj().equals(txtCNPJ.getText())) {
                                txtNomeDono.setText(e.getDono().getNome());
                                txtCPF.setText(e.getDono().getCpf());
                                txtTelefone.setText(e.getDono().getTelefone());
                                txtSenha.setText(e.getDono().getSenha());
                                empresaSelecionada = e;
                        }
                }
                atualizarTabelaFilial();

        }// GEN-LAST:event_tblEmpresasMouseClicked

        private void tblFiliaisMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblFiliaisMouseClicked
                Integer selecao = JOptionPane.showConfirmDialog(null, "Deseja acessar essa filial?");

                if (selecao == 0) {
                        int linhaSelecionada = tblFiliais.getSelectedRow();

                        Object valorCelula1 = tblFiliais.getValueAt(linhaSelecionada, 0);
                        this.admOuDono.setFilial(empresaSelecionada.selecionarFiliais(valorCelula1.toString()));
                        FrmMenu menu = new FrmMenu(admOuDono);
                        menu.setVisible(true);
                        this.dispose();
                }
        }// GEN-LAST:event_tblFiliaisMouseClicked

        private void btnNovaFilialActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovaFilialActionPerformed
                if (!txtCNPJ.getText().equals("") && !txtCNPJ.getText().equals("  .   .   /    -  ")) {

                        String nomeFilial = JOptionPane.showInputDialog(null,
                                        "Digite o nome da filia: ",
                                        JOptionPane.PLAIN_MESSAGE);
                        String enderecoFilial = JOptionPane.showInputDialog(null,
                                        "Digite o endereco da filial:",
                                        JOptionPane.PLAIN_MESSAGE);

                        if (nomeFilial != null && enderecoFilial != null) {
                                Filial objFilia = new Filial(nomeFilial, enderecoFilial);
                                for (Empresa e : Main.listaEmpresas) {
                                        if (e.getCnpj().equals(txtCNPJ.getText())) {
                                                e.getListaFiliais().add(objFilia);
                                                JOptionPane.showMessageDialog(null, "Filial cadastrada com sucesso!");
                                                break;
                                        }
                                }
                        }

                        atualizarTabelaFilial();
                } else {
                        JOptionPane.showMessageDialog(null, "Selecione uma empresa");
                }
        }// GEN-LAST:event_btnNovaFilialActionPerformed

        private void lblLinkAuthMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLinkAuthMouseClicked
                FrmListaAuth frm = new FrmListaAuth(this.admOuDono);
                frm.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_lblLinkAuthMouseClicked

        private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblSairMouseClicked
                FrmLogin frm = new FrmLogin();
                frm.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_lblSairMouseClicked

        private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
                this.setExtendedState(this.MAXIMIZED_BOTH);
                this.setVisible(true);
        }// GEN-LAST:event_formWindowActivated

        private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
                boolean naoExiste = true;
                if (!txtCNPJ.getText().equals("  .   .   /    -  ") && !txtCPF.getText().equals("   .   .   -  ")
                                && !txtTelefone.getText().equals("(  )       -    ")
                                && !txtNome.getText().equals("") && !txtNomeDono.getText().equals("")
                                && !txtSenha.getText().equals("")) {
                        for (Empresa e : Main.listaEmpresas) {
                                System.out.println(e.getCnpj() + " " + txtCNPJ.getText());
                                if (e.getCnpj().equals(txtCNPJ.getText())) {
                                        e.setNome(txtNome.getText());
                                        e.setCnpj(txtCNPJ.getText());
                                        e.getDono().setNome(txtNomeDono.getText());
                                        e.getDono().setTelefone(txtTelefone.getText());
                                        e.getDono().setCpf(txtCPF.getText());
                                        e.getDono().setSenha(txtSenha.getText());
                                        naoExiste = false;
                                        JOptionPane.showMessageDialog(null, "Empresa atualizada com sucesso!");
                                }
                        }
                        if (naoExiste) {
                                Funcionario dono = new Gerente(txtCPF.getText(), txtNomeDono.getText(), null,
                                                txtTelefone.getText(), "Dono",
                                                txtSenha.getText(), null);
                                Empresa objEmpresa = new Empresa(txtCNPJ.getText(), txtNome.getText(), dono);
                                Main.usuarios.add(dono);
                                Main.listaEmpresas.add(objEmpresa);
                                JOptionPane.showMessageDialog(null, "Empresa cadastrada com sucesso!");
                                empresaSelecionada = objEmpresa;
                        }
                        atualizarTabelaEmpresa();
                        atualizarTabelaFilial();
                        txtCNPJ.setText("");
                        txtCPF.setText("");
                        txtNome.setText("");
                        txtNomeDono.setText("");
                        txtSenha.setText("");
                        txtSenha.setText("");
                        txtTelefone.setText("");
                }
        }// GEN-LAST:event_btnSalvarActionPerformed

        private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
                if (!txtCNPJ.getText().equals("")) {
                        for (Empresa f : Main.listaEmpresas) {
                                if (f.getCnpj().equals(txtCNPJ.getText())) {
                                        Main.listaEmpresas.remove(f);
                                        JOptionPane.showMessageDialog(null, "Empresa excluida com sucesso!");
                                        break;
                                }
                        }

                        atualizarTabelaEmpresa();
                        atualizarTabelaFilial();

                        txtCNPJ.setText("");
                        txtCPF.setText("");
                        txtNome.setText("");
                        txtNomeDono.setText("");
                        txtSenha.setText("");
                        txtSenha.setText("");
                        txtTelefone.setText("");
                }
        }// GEN-LAST:event_btnExcluirActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmListaEmpresas.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmListaEmpresas.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmListaEmpresas.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmListaEmpresas.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FrmListaEmpresas(
                                                new Gerente("07150760279", "Ludivik", "Ludivk@gmail.com", "92996140802",
                                                                "Administrador", "123", null))
                                                .setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnExcluir;
        private javax.swing.JButton btnNovaFilial;
        private javax.swing.JButton btnSalvar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel lblOu;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel lblLinkAuth;
        private javax.swing.JLabel lblSair;
        private javax.swing.JTable tblEmpresas;
        private javax.swing.JTable tblFiliais;
        private javax.swing.JFormattedTextField txtCNPJ;
        private javax.swing.JFormattedTextField txtCPF;
        private javax.swing.JTextField txtNome;
        private javax.swing.JTextField txtNomeDono;
        private javax.swing.JTextField txtSenha;
        private javax.swing.JFormattedTextField txtTelefone;
        // End of variables declaration//GEN-END:variables
}
