/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unicamp.ic.mc322.view;

import unicamp.ic.mc322.view.cadastro.FrmCadastroClientePJ;
import unicamp.ic.mc322.view.cadastro.FrmCadastroFornecedor;
import unicamp.ic.mc322.view.cadastro.FrmCadastroFuncionario;
import unicamp.ic.mc322.view.cadastro.FrmCadastroProdutos;
import unicamp.ic.mc322.view.lista.FrmConsultaClientePF;
import unicamp.ic.mc322.view.lista.FrmConsultaClientePJ;
import unicamp.ic.mc322.view.lista.FrmConsultaFornecedor;
import unicamp.ic.mc322.view.lista.FrmConsultaFuncionario;
import unicamp.ic.mc322.view.lista.FrmConsultaProdutos;
import unicamp.ic.mc322.view.sistema.FrmVendas;

import java.awt.Graphics;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

import unicamp.ic.mc322.model.AdmEstoque;
import unicamp.ic.mc322.model.Funcionario;
import unicamp.ic.mc322.model.Gerente;
import unicamp.ic.mc322.model.Vendedor;
import unicamp.ic.mc322.view.cadastro.FrmCadastroClientePF;

public class FrmMenu extends javax.swing.JFrame {

    private Funcionario func;

    public FrmMenu(Funcionario func) {
        initComponents();
        this.func = func;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // ImageIcon icon = new
        // ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Fundo.jpeg"));

        // Image image = icon.getImage();
        painel_desktop = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                // g.drawImage(image, 0,0, getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnPrincipal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }

            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painel_desktop.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seja bem-vindo");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Logo.png"))); // NOI18N

        lblNomeUsuario.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        lblNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeUsuario.setText("<<NomeUsuario>>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 999,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeUsuario)
                                .addGap(81, 81, 81)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel3))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblNomeUsuario)
                                                        .addComponent(jLabel1))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        painel_desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel_desktopLayout = new javax.swing.GroupLayout(painel_desktop);
        painel_desktop.setLayout(painel_desktopLayout);
        painel_desktopLayout.setHorizontalGroup(
                painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        painel_desktopLayout.setVerticalGroup(
                painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                painel_desktopLayout.createSequentialGroup()
                                        .addContainerGap(567, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

        jMenuBar1.setBackground(new java.awt.Color(217, 217, 217));

        jmnPrincipal.setText("Sair");
        jmnPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnPrincipalMouseClicked(evt);
            }
        });
        jmnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnPrincipalActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmnPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painel_desktop));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painel_desktop));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
        this.setExtendedState(this.MAXIMIZED_BOTH);
        lblNomeUsuario.setText(this.func.getNome());
        this.setVisible(true);
    }// GEN-LAST:event_formWindowActivated

    private void jmnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmnPrincipalActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jmnPrincipalActionPerformed

    private void jmnPrincipalMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jmnPrincipalMouseClicked
        int op;
        op = JOptionPane.showConfirmDialog(null, "Você tem certeza que desja sair?");
        if (op == 0) {
            System.exit(0);
        }
    }// GEN-LAST:event_jmnPrincipalMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened

        JMenu Sistemas = new JMenu();
        Sistemas.setText("Sistemas");
        Sistemas.setFont(new java.awt.Font("Segoe UI", 0, 16));
        Sistemas.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Configuracoes.png")));

        JMenu Funcionario = new JMenu();
        Funcionario.setText("Funcionario");
        Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16));
        Funcionario.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Funcionario.png")));

        JMenu Produtos = new JMenu();
        Produtos.setText("Produtos");
        Produtos.setFont(new java.awt.Font("Segoe UI", 0, 16));
        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Produto.png")));

        JMenu Clientes = new JMenu();
        Clientes.setText("Clientes");
        Clientes.setFont(new java.awt.Font("Segoe UI", 0, 16));
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Cliente.png")));

        JMenu Fornecedores = new JMenu();
        Fornecedores.setText("Fornecedores");
        Fornecedores.setFont(new java.awt.Font("Segoe UI", 0, 16));
        Fornecedores
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicamp/ic/mc322/imagens/Fornecedor.png")));

        FrmCadastroClientePJ frm1 = new FrmCadastroClientePJ();
        FrmCadastroClientePF frm12 = new FrmCadastroClientePF();
        FrmCadastroFornecedor frm2 = new FrmCadastroFornecedor(this.func);
        FrmCadastroFuncionario frm3 = new FrmCadastroFuncionario(this.func);
        FrmCadastroProdutos frm4 = new FrmCadastroProdutos();

        FrmConsultaClientePF frm5 = new FrmConsultaClientePF();
        FrmConsultaClientePJ frm52 = new FrmConsultaClientePJ();
        FrmConsultaFornecedor frm6 = new FrmConsultaFornecedor();
        FrmConsultaFuncionario frm7 = new FrmConsultaFuncionario(this.func);
        FrmConsultaProdutos frm8 = new FrmConsultaProdutos();

        FrmVendas frm10 = new FrmVendas();
        if (this.func instanceof Gerente) {
            Produtos.add(frm4.MenuItem());
            Produtos.add(frm8.MenuItem());

            Clientes.add(frm1.MenuItem());
            Clientes.add(frm12.MenuItem());
            Clientes.add(frm5.MenuItem());

            Fornecedores.add(frm2.MenuItem());
            Fornecedores.add(frm6.MenuItem());

            Sistemas.add(frm10.MenuItem());

            Funcionario.add(frm3.MenuItem());
            Funcionario.add(frm7.MenuItem());

            jMenuBar1.add(Produtos);
            jMenuBar1.add(Fornecedores);
            jMenuBar1.add(Clientes);
            jMenuBar1.add(Funcionario);

            jMenuBar1.add(Sistemas);
        } else if (this.func instanceof Vendedor) {
            Produtos.add(frm8.MenuItem());

            Clientes.add(frm1.MenuItem());
            Clientes.add(frm12.MenuItem());
            Clientes.add(frm5.MenuItem());
            Clientes.add(frm52.MenuItem());

            Sistemas.add(frm10.MenuItem());

            jMenuBar1.add(Produtos);
            jMenuBar1.add(Clientes);

            jMenuBar1.add(Sistemas);
        } else if (this.func instanceof AdmEstoque) {
            Produtos.add(frm4.MenuItem());
            Produtos.add(frm8.MenuItem());

            Fornecedores.add(frm2.MenuItem());
            Fornecedores.add(frm6.MenuItem());

            jMenuBar1.add(Produtos);

            jMenuBar1.add(Fornecedores);

        }
    }// GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMenu(new Gerente("07150760279", "Ludivik", null, null, "Gerente", null, null))
                    .setVisible(true);
        });
    }

    public Funcionario getFunc() {
        return func;
    }

    public void setFunc(Funcionario func) {
        this.func = func;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jmnPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JDesktopPane painel_desktop;
    // End of variables declaration//GEN-END:variables
}
