/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unicamp.ic.mc322.view.cadastro;

import javax.swing.JMenuItem;

import unicamp.ic.mc322.model.AdmEstoque;
import unicamp.ic.mc322.model.Funcionario;
import unicamp.ic.mc322.model.Gerente;
import unicamp.ic.mc322.model.Vendedor;
import unicamp.ic.mc322.util.JMenuFrame;

public class FrmCadastroFuncionario extends javax.swing.JFrame {

        private Funcionario objFuncionario;

        private Funcionario funcionarioLogado;

        public Funcionario getObjFuncionario() {
                return objFuncionario;
        }

        public void setObjFuncionario(Funcionario objFuncionario) {
                this.objFuncionario = objFuncionario;
                txtNome.setText(objFuncionario.getNome());
                txtCpf.setText(objFuncionario.getCpf());
                txtSenha.setText(objFuncionario.getSenha());
                txtEmail.setText(objFuncionario.getEmail());
                txtCel.setText(objFuncionario.getTelefone());
        }

        /**
         * Creates new form FrmCadastroFuncionario
         */
        public FrmCadastroFuncionario(Funcionario funcionarioLogado) {
                initComponents();
                this.funcionarioLogado = funcionarioLogado;
        }

        public JMenuItem MenuItem() {
                return JMenuFrame.CreateMenuItem("Cadastrar Funcionarios", this);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                painel_dados = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                txtCpf = new javax.swing.JFormattedTextField();
                jLabel4 = new javax.swing.JLabel();
                txtCel = new javax.swing.JFormattedTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                txtNome = new javax.swing.JTextField();
                txtEmail = new javax.swing.JTextField();
                jLabel17 = new javax.swing.JLabel();
                txtSenha = new javax.swing.JPasswordField();
                jLabel18 = new javax.swing.JLabel();
                cmbCargo = new javax.swing.JComboBox<>();
                btnSalvar = new javax.swing.JButton();
                btnExcluir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(217, 217, 217));

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Cadastro de Funcionários");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(20, Short.MAX_VALUE)));

                painel_dados.setBackground(new java.awt.Color(255, 255, 255));
                painel_dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel3.setText("Nome:");

                try {
                        txtCpf.setFormatterFactory(
                                        new javax.swing.text.DefaultFormatterFactory(
                                                        new javax.swing.text.MaskFormatter("###.###.###-##")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel4.setText("E-mail:");

                try {
                        txtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                                        new javax.swing.text.MaskFormatter("(##) #### - ####")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel5.setText("CPF:");

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel8.setText("Celular:");

                txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel17.setText("Senha:");

                txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel18.setText("Cargo:");

                cmbCargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Gerente", "Vendedor", "AdmEstoque" }));

                javax.swing.GroupLayout painel_dadosLayout = new javax.swing.GroupLayout(painel_dados);
                painel_dados.setLayout(painel_dadosLayout);
                painel_dadosLayout.setHorizontalGroup(
                                painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painel_dadosLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel17)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtSenha,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                169,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(38, 38, 38)
                                                                                                .addComponent(jLabel18)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(cmbCargo,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                183,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(txtCpf,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                153,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(painel_dadosLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel4))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(painel_dadosLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(painel_dadosLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(txtNome,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                316,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(2, 2, 2))
                                                                                                                .addComponent(txtEmail,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                316,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(30, 30, 30)
                                                                                                .addComponent(jLabel8)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtCel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                141,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 354, Short.MAX_VALUE)));
                painel_dadosLayout.setVerticalGroup(
                                painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painel_dadosLayout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txtCpf,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(jLabel5)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel3)
                                                                                                .addGap(26, 26, 26)
                                                                                                .addComponent(jLabel4))
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(txtNome,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(painel_dadosLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(painel_dadosLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(txtCel,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel8))
                                                                                                                .addComponent(txtEmail,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel17)
                                                                                .addComponent(txtSenha,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel18)
                                                                                .addComponent(cmbCargo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                23,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(223, Short.MAX_VALUE)));

                btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnSalvar.setText("Salvar");
                btnSalvar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSalvarActionPerformed(evt);
                        }
                });

                btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnExcluir.setText("Excluir");
                btnExcluir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExcluirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(painel_dados,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(327, 327, 327)
                                                                                                .addComponent(btnSalvar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                108,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(74, 74, 74)
                                                                                                .addComponent(btnExcluir,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                108,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                70,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(painel_dados,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(btnSalvar,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnExcluir,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(21, 21, 21)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnExcluirActionPerformed

        private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
                if (cmbCargo.getSelectedItem().toString().equals("Gerente")) {
                        objFuncionario = new Gerente(txtCpf.getText(), txtNome.getText(), txtEmail.getText(),
                                        txtCel.getText(),
                                        cmbCargo.getSelectedItem().toString(), txtSenha.getPassword().toString(),
                                        this.funcionarioLogado.getFilial());
                } else if (cmbCargo.getSelectedItem().toString().equals("Vendedor")) {
                        objFuncionario = new Vendedor(txtCpf.getText(), txtNome.getText(), txtEmail.getText(),
                                        txtCel.getText(),
                                        cmbCargo.getSelectedItem().toString(), txtSenha.getPassword().toString(),
                                        this.funcionarioLogado.getFilial());
                } else if (cmbCargo.getSelectedItem().toString().equals("AdmEstoque")) {
                        objFuncionario = new AdmEstoque(txtCpf.getText(), txtNome.getText(), txtEmail.getText(),
                                        txtCel.getText(),
                                        cmbCargo.getSelectedItem().toString(), txtSenha.getPassword().toString(),
                                        this.funcionarioLogado.getFilial());
                }

                funcionarioLogado.getFilial().addFuncionario(objFuncionario);
                System.out.println(funcionarioLogado.getFilial().listarFuncionario().size());

                txtCel.setText("");
                txtCpf.setText("");
                txtEmail.setText("");
                txtNome.setText("");
                txtSenha.setText("");

        }// GEN-LAST:event_btnSalvarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FrmCadastroFuncionario(new Gerente(null, null, null, null, null, null, null))
                                                .setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnExcluir;
        private javax.swing.JButton btnSalvar;
        private javax.swing.JComboBox<String> cmbCargo;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel painel_dados;
        private javax.swing.JFormattedTextField txtCel;
        private javax.swing.JFormattedTextField txtCpf;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtNome;
        private javax.swing.JPasswordField txtSenha;
        // End of variables declaration//GEN-END:variables
}
