/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unicamp.ic.mc322.view.cadastro;

import java.awt.Color;
import javax.swing.JMenuItem;

import unicamp.ic.mc322.model.AdmEstoque;
import unicamp.ic.mc322.model.Fornecedor;
import unicamp.ic.mc322.model.Funcionario;
import unicamp.ic.mc322.model.Gerente;
import unicamp.ic.mc322.model.Vendedor;
import unicamp.ic.mc322.util.JMenuFrame;

public class FrmCadastroFornecedor extends javax.swing.JFrame {

        private Funcionario funcionarioLogado;

        private Fornecedor objFornecedor;

        public Funcionario getFuncionarioLogado() {
                return funcionarioLogado;
        }

        public void setFuncionarioLogado(Funcionario funcionarioLogado) {
                this.funcionarioLogado = funcionarioLogado;
        }

        public Fornecedor getObjFornecedor() {
                return objFornecedor;
        }

        public void setObjFornecedor(Fornecedor objFornecedor) {
                this.objFornecedor = objFornecedor;
        }

        public FrmCadastroFornecedor(Funcionario funcionarioLogado) {
                initComponents();
                this.getContentPane().setBackground(Color.WHITE);
                this.funcionarioLogado = funcionarioLogado;
        }

        public JMenuItem MenuItem() {
                return JMenuFrame.CreateMenuItem("Cadastrar Fornecedor", this);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                painel_dados = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtcel = new javax.swing.JFormattedTextField();
                jLabel6 = new javax.swing.JLabel();
                txtCnpj = new javax.swing.JFormattedTextField();
                jLabel8 = new javax.swing.JLabel();
                txtNome = new javax.swing.JTextField();
                txtemail = new javax.swing.JTextField();
                txtend = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                btnSalvar = new javax.swing.JButton();
                btnExcluir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Cadastro de Clientes");

                jPanel1.setBackground(new java.awt.Color(217, 217, 217));

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Cadastro de Fornecedores");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(703, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(20, Short.MAX_VALUE)));

                painel_dados.setBackground(new java.awt.Color(255, 255, 255));
                painel_dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar"));

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel3.setText("Nome:");

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel4.setText("E-mail:");

                try {
                        txtcel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                                        new javax.swing.text.MaskFormatter("(##) #### - ####")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel6.setText("CNPJ:");

                try {
                        txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                                        new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                txtCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel8.setText("Celular:");

                txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                txtemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                txtend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel10.setText("Endereço:");

                javax.swing.GroupLayout painel_dadosLayout = new javax.swing.GroupLayout(painel_dados);
                painel_dados.setLayout(painel_dadosLayout);
                painel_dadosLayout.setHorizontalGroup(
                                painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painel_dadosLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel10)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtend,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                316,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel3)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtNome,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                316,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel4)
                                                                                                .addGroup(painel_dadosLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(painel_dadosLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(379, 379,
                                                                                                                                                379)
                                                                                                                                .addComponent(jLabel8)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(txtcel,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                141,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                painel_dadosLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(txtemail,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                316,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(255, 255,
                                                                                                                                                                255))))
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel6)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtCnpj,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                169,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(350, Short.MAX_VALUE)));

                painel_dadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
                                new java.awt.Component[] { txtNome, txtemail });

                painel_dadosLayout.setVerticalGroup(
                                painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painel_dadosLayout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtCnpj,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel6))
                                                                .addGap(13, 13, 13)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(txtNome,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(16, 16, 16)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel4)
                                                                                .addGroup(painel_dadosLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(txtemail,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(painel_dadosLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtcel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel8))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(painel_dadosLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(txtend,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(163, Short.MAX_VALUE)));

                painel_dadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
                                new java.awt.Component[] { txtNome, txtemail });

                btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnSalvar.setText("Salvar/Novo");
                btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnSalvarMouseClicked(evt);
                        }
                });

                btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnExcluir.setText("Excluir");
                btnExcluir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExcluirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(338, 338, 338)
                                                                .addComponent(btnSalvar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                108,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(68, 68, 68)
                                                                .addComponent(btnExcluir,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                108,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(painel_dados,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                448,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnExcluir,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnSalvar,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29))
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                                .addContainerGap(142,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(painel_dados,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(111,
                                                                                                                Short.MAX_VALUE))));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSalvarMouseClicked
                objFornecedor = new Fornecedor(txtCnpj.getText(), txtNome.getText(), txtemail.getText(),
                                txtcel.getText(),
                                txtend.getText());

                funcionarioLogado.getFilial().listarFornecedores().add(objFornecedor);

                txtCnpj.setText("");
                txtNome.setText("");
                txtemail.setText("");
                txtcel.setText("");
                txtend.setText("");
        }// GEN-LAST:event_btnSalvarMouseClicked

        private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnExcluirActionPerformed

        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Windows".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFornecedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFornecedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFornecedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmCadastroFornecedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FrmCadastroFornecedor(new Gerente(null, null, null, null, null, null, null))
                                                .setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnExcluir;
        private javax.swing.JButton btnSalvar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel painel_dados;
        private javax.swing.JFormattedTextField txtCnpj;
        private javax.swing.JTextField txtNome;
        private javax.swing.JFormattedTextField txtcel;
        private javax.swing.JTextField txtemail;
        private javax.swing.JTextField txtend;
        // End of variables declaration//GEN-END:variables
}
